### ISSUE TITLE
ComponentAttacher not keeping materials after neos cleanup

### ISSUE THREAD

**Issue by 3x1t-5tyl3** [3x1t-5tyl3/The-Exitian-MultiTool#16]
### Describe the bug?

ComponentAttacher not keeping materials after neos cleanup

### Relevant issues

-

### To Reproduce

Spawn ComponentAttacher

### Expected behavior

It has proper materials even if neos does autocleanup

### Screenshots

https://media.discordapp.net/attachments/887002920573337661/887003200320856074/2021-09-13_01.12.39.jpg?width=512&height=910

### How often does it happen?

Always

### Tool Version Number (Found in the bottom left of the main menu)

11092021

### Did this work before?

I Don't Know

**Comment by RobertBaruch** [comment]
Can confirm.

**Comment by 3x1t-5tyl3** [comment]
Fixed in B-19092021.0!
Hopefully. Let me know if it still nukes it.

**Comment by 3x1t-5tyl3** [comment]
Should actuaally be fixed now in 25092021.0
Closing this.
