### ISSUE TITLE
Instructions say "Spawn the Exitian" but it is hidden under "Template"

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#17]
### Describe the bug?

Pedantic, I know, but may as well get it consistent :)

### Relevant issues

None.

### To Reproduce

Look at the instructions.

### Expected behavior

The instructions specifies that it is under Template.

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

N/A

### Did this work before?

No

**Comment by 3x1t-5tyl3** [comment]
Fixed in 14092021-0. Thanks <3
I moved it and removed the UIX button. Should hopefully be a lot clearer now!
