### ISSUE TITLE
Instructions refer to "ny submenu". I have no idea what that means.

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#18]
### Describe the bug?

I am not sure what "ny submenu" means. Even if it should have been "your submenu", what is that?

### Relevant issues

None.

### To Reproduce

Look at the instructions.

### Expected behavior

The instructions make sense :>

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

N/A

### Did this work before?

No

**Comment by RobertBaruch** [comment]
Suggestion: "as a subitem in your avatar's context menu"

**Comment by 3x1t-5tyl3** [comment]
Ahhhh I typed it in vr. #oops. I'll fix it :)

**Comment by 3x1t-5tyl3** [comment]
Fixed in 14092021-0. Thanks <3
