### ISSUE TITLE
Component attacher seems not to attach component once on an empty object

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#21]
### Describe the bug?

It seems that the first time I attach a component to an empty object, the component doesn't get attached. Subsequently, components do get attached.

### Relevant issues

None

### To Reproduce

1. Create an empty object.
2. Attach a component
3. The component does not appear.
4. Attach a component again.
5. The component appears this time.

### Expected behavior

The component gets attached.

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

B-13092021.0

### Did this work before?

Yes

**Comment by RobertBaruch** [comment]
Note, I've also had this happen on a newly opened object in the inspector.

**Comment by 3x1t-5tyl3** [comment]
Yeah I'm aware of the issue. I'll push an update later to fix it (hopefully)

**Comment by 3x1t-5tyl3** [comment]
Fixed in  B-19092021.0!
