### ISSUE TITLE
Grabbing a LogiX node with the LogiX tooltip rotates it 90 degrees.

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#31]
### Describe the bug?

When grabbing a newly-spawned LogiX node with the LogiX tooltip, the node rotates sideways 90 degrees, requiring me to pull the node onto the tip, rotate my hand 90 degrees, and place it on the redprint.

### Relevant issues

N/A

### To Reproduce

1. Activate the LogiX tooltip.
2. Spawn a node.
3. Laser-grab the node.
4. Observe the node rotate 90 degrees.

### Expected behavior

The node should not change orientation when grabbed.

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

B-25092021.1

### Did this work before?

Yes

### If it worked before, on which version?

B-19092021.2 (at least)

**Comment by 3x1t-5tyl3** [comment]
Known. I'll fix it later tonight by being able to disable the gridsnapping alltogethjer. For now just dequipt the tool. ETA 1 hr.

**Comment by 3x1t-5tyl3** [comment]
Fixed implicitly by disabling snapping in B-26092021.0.
Snapping can be re-enabling in the context menu.

**Comment by RobertBaruch** [comment]
I think what's happening is that my right hand's neutral position is with the thumb pointing up, while the node seems to align itself with an axis similar to the line of knuckles. So if I rotate my right hand 90 degrees counterclockwise, the node goes the right way up. I can get used to it.
