### ISSUE TITLE
Please default to false the blue mesh that appears when grabbing LogiX nodes

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#32]
### Describe the bug?

The blue mesh when grabbing and moving LogiX nodes is distracting to me.

### Relevant issues

N/A

### To Reproduce

1. Grab LogiX nodes with the LogiX tooltip.
2. Observe the blue mesh surrounding the node.
3. It hurts my eyes.

### Expected behavior

At least the ability to turn it off, if it doesn't default to off.

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

B-25092021.1

### Did this work before?

Yes

### If it worked before, on which version?

B-19092021.2 (at least)

**Comment by 3x1t-5tyl3** [comment]
Tweaked the Color in B-26092021.0.
Let me know if it's a bit better.

**Comment by RobertBaruch** [comment]
It's somewhat better, but it's still a bit intrusive to me. Ideally it would be very subtle.
