### ISSUE TITLE
Ability to turn off snapgrid

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#33]
### Why add it?

When using a redprint, there's not a whole lot of reason to use another snapgrid, since the redprint snaps to a grid anyway. It's especially disconcerting when the redprint is on a different scale, since then the snapgrid seems too big.

**Comment by 3x1t-5tyl3** [comment]
LogiXTip -> Extra -> SnapGrid allows you turn it on/off.
For now I'll be keeping it on my tool. Sorry.

**Comment by RobertBaruch** [comment]
Perfect, thank you!
