### ISSUE TITLE
Logix > Extras > Gridsnap misspelled

### ISSUE THREAD

**Issue by RobertBaruch** [3x1t-5tyl3/The-Exitian-MultiTool#34]
### Describe the bug?

It shows as Grisnap, not Gridsnap

### Relevant issues

N/A

### To Reproduce

N/A

### Expected behavior

N/A

### How often does it happen?

Always

### Does the bug persist after respawning the tool?

Yes

### Tool Version Number (Found in the bottom left of the main menu)

B-26092021.0

### Did this work before?

No

**Comment by 3x1t-5tyl3** [comment]
Implicitly fixed in B-041021.0 by removing gridsnapping.
